"""H3KnowledgeStore — SQLite + WAL store.

Concurrency model
-----------------
SQLite with WAL (Write-Ahead Log) journal mode supports:
  - Multiple concurrent readers (no blocking between reads)
  - One writer at a time (serialised by the OS-level WAL mechanism)
  - Readers never block writers; writers never block readers

This is exactly what we need: Streamlit (many reads) + ingestor (bulk writes)
can run simultaneously without lock errors.

Connection handling
-------------------
Every public method opens its own sqlite3 connection, runs the statement, and
commits/closes immediately.  This keeps the write window to microseconds per
call.  An in-process threading.Lock() serialises concurrent writes within the
same Python process (Streamlit's multi-thread rendering).

The `check_same_thread=False` flag is required because Streamlit runs each
component render in its own thread; we handle safety ourselves with _lock.

pandas integration
------------------
fetchdf() uses pandas.read_sql() which accepts a sqlite3 connection.
"""
from __future__ import annotations

import logging
import sqlite3
import threading
from pathlib import Path

import pandas as pd

from airos.drivers.store.schema import DB_PATH, ALL_DDL

logger = logging.getLogger(__name__)

_lock = threading.Lock()
_schema_initialised: dict[str, bool] = {}


def _connect(db_path: Path, *, read_only: bool = False) -> sqlite3.Connection:
    """Open a SQLite connection with WAL mode and sensible defaults."""
    if read_only:
        uri = f"file:{db_path}?mode=ro"
        conn = sqlite3.connect(uri, uri=True, check_same_thread=False,
                               timeout=10.0, detect_types=sqlite3.PARSE_DECLTYPES)
    else:
        conn = sqlite3.connect(str(db_path), check_same_thread=False,
                               timeout=30.0, detect_types=sqlite3.PARSE_DECLTYPES)
        conn.execute("PRAGMA journal_mode=WAL")
        conn.execute("PRAGMA synchronous=NORMAL")
        conn.execute("PRAGMA busy_timeout=30000")
    conn.row_factory = sqlite3.Row
    return conn


def _ensure_schema(db_path: Path) -> None:
    key = str(db_path)
    if _schema_initialised.get(key):
        return
    try:
        db_path.parent.mkdir(parents=True, exist_ok=True)
        with _connect(db_path) as conn:
            for ddl in ALL_DDL:
                for stmt in ddl.strip().split(";"):
                    stmt = stmt.strip()
                    if stmt:
                        try:
                            conn.execute(stmt)
                        except Exception as exc:
                            logger.debug("Schema DDL non-fatal: %s", exc)
            conn.commit()
        # ── Column migrations (idempotent ALTER TABLE) ──────────────────
        # Add new columns to existing tables without recreating them.
        # Each ALTER TABLE is wrapped in try/except — SQLite raises
        # "duplicate column name" if the column already exists.
        _migrations = [
            "ALTER TABLE h3_metadata ADD COLUMN area_name TEXT",
            # Insight fields generated by the agent but previously not persisted
            "ALTER TABLE h3_insights ADD COLUMN recommended_actions_json TEXT",
            "ALTER TABLE h3_insights ADD COLUMN uncertainty_notes_json TEXT",
            # Phase 1: data provenance on signals
            "ALTER TABLE h3_signals ADD COLUMN data_quality TEXT NOT NULL DEFAULT 'unknown'",
            # Phase 1/2: hypothesis framing + outcome tracking on insights
            "ALTER TABLE h3_insights ADD COLUMN priority_tier TEXT NOT NULL DEFAULT 'medium'",
            "ALTER TABLE h3_insights ADD COLUMN hypothesis_chain_json TEXT",
            "ALTER TABLE h3_insights ADD COLUMN outcome_status TEXT NOT NULL DEFAULT 'open'",
            "ALTER TABLE h3_insights ADD COLUMN closed_by TEXT",
            "ALTER TABLE h3_insights ADD COLUMN closed_at TEXT",
            # Driver conformance gate — per-ingest conformance result
            "ALTER TABLE h3_ingest_log ADD COLUMN conformance_ok INTEGER",
            "ALTER TABLE h3_ingest_log ADD COLUMN conformance_failures TEXT",
            # Decision packet structured evidence fields (spec: h3_packets §Evidence)
            "ALTER TABLE h3_packets ADD COLUMN evidence_json TEXT",
            "ALTER TABLE h3_packets ADD COLUMN safety_gates_json TEXT",
            "ALTER TABLE h3_packets ADD COLUMN blocked_uses_json TEXT",
        ]
        with _connect(db_path) as conn:
            for mig in _migrations:
                try:
                    conn.execute(mig)
                    conn.commit()
                    logger.debug("Migration applied: %s", mig)
                except Exception:
                    pass   # column already exists — harmless

        _schema_initialised[key] = True
        logger.info("H3KnowledgeStore (SQLite/WAL) ready at %s", db_path)
    except Exception as exc:
        logger.warning("Schema init failed: %s", exc)


# ---------------------------------------------------------------------------
# Store class
# ---------------------------------------------------------------------------

class H3KnowledgeStore:
    """SQLite-backed H3 knowledge store.

    Transient connections — each method opens, runs, commits, closes.
    Use write_batch() for bulk inserts (faster — single transaction).
    """

    def __init__(self, db_path: Path = DB_PATH) -> None:
        db_path.parent.mkdir(parents=True, exist_ok=True)
        self._db_path = db_path
        _ensure_schema(db_path)

    @classmethod
    def get(cls, db_path: Path = DB_PATH) -> "H3KnowledgeStore":
        return cls(db_path)

    @classmethod
    def get_writer(cls, db_path: Path = DB_PATH) -> "H3KnowledgeStore":
        return cls(db_path)

    @classmethod
    def reset(cls) -> None:
        _schema_initialised.clear()

    # ------------------------------------------------------------------
    # Write
    # ------------------------------------------------------------------

    def execute(self, sql: str, params: list | None = None) -> None:
        """Execute one write statement and commit."""
        with _lock:
            try:
                with _connect(self._db_path) as conn:
                    conn.execute(sql, params or [])
                    conn.commit()
            except Exception as exc:
                logger.warning("H3Store execute error: %s | %.120s", exc, sql)

    def write_batch(self, sql: str, rows: list[list]) -> int:
        """Execute many rows in a single transaction. Returns rows written."""
        if not rows:
            return 0
        with _lock:
            try:
                with _connect(self._db_path) as conn:
                    conn.executemany(sql, rows)
                    conn.commit()
                    return len(rows)
            except Exception as exc:
                logger.warning("H3Store write_batch error: %s | %.120s", exc, sql)
                return 0

    # ------------------------------------------------------------------
    # Read
    # ------------------------------------------------------------------

    def fetchdf(self, sql: str, params: list | None = None) -> pd.DataFrame:
        """Execute a SELECT and return a pandas DataFrame."""
        try:
            # SQLite read-only opens don't block writers in WAL mode
            conn = _connect(self._db_path, read_only=True)
            try:
                return pd.read_sql(sql, conn, params=params)
            finally:
                conn.close()
        except Exception as exc:
            logger.warning("H3Store fetchdf error: %s | %.120s", exc, sql)
            return pd.DataFrame()

    def fetchone(self, sql: str, params: list | None = None):
        """Execute a SELECT and return the first row as a tuple, or None."""
        try:
            conn = _connect(self._db_path, read_only=True)
            try:
                cur = conn.execute(sql, params or [])
                row = cur.fetchone()
                return tuple(row) if row else None
            finally:
                conn.close()
        except Exception as exc:
            logger.warning("H3Store fetchone error: %s", exc)
            return None

    # ------------------------------------------------------------------
    # Health
    # ------------------------------------------------------------------

    def table_counts(self) -> dict[str, int]:
        tables = [
            "h3_metadata", "h3_signals", "h3_assessments",
            "h3_packets", "h3_insights", "h3_outcomes",
            "h3_ingest_log", "h3_siting_candidates", "h3_analysis_requests",
        ]
        counts: dict[str, int] = {}
        for t in tables:
            try:
                row = self.fetchone(f"SELECT count(*) FROM {t}")
                counts[t] = int(row[0]) if row else 0
            except Exception:
                counts[t] = 0  # table may not exist yet in older DBs
        return counts

    def is_available(self) -> bool:
        return self.fetchone("SELECT 1") is not None
